export const Users = [
  {
    id: 1,
    profilePicture: "assest/persons/1.jpg",
    username: "Alex Morgan",
  },
  {
    id: 2,
    profilePicture: "assest/persons/2.jpg",
    username: "Ben Carter",
  },
  {
    id: 3,
    profilePicture: "assest/persons/3.jpg",
    username: "Chloe Davis",
  },
  {
    id: 4,
    profilePicture: "assest/persons/4.jpg",
    username: "David Evans",
  },
  {
    id: 5,
    profilePicture: "assest/persons/p1.jpg",
    username: "Emily Frank",
  },
  {
    id: 6,
    profilePicture: "assest/persons/p2.jpg",
    username: "Fiona Green",
  },
  {
    id: 7,
    profilePicture: "assest/persons/p3.jpg",
    username: "George Hill",
  },
  {
    id: 8,
    profilePicture: "assest/persons/p4.jpg",
    username: "Hannah Irving",
  },
  {
    id: 9,
    profilePicture: "assest/persons/p5.jpg",
    username: "Ian Jenkins",
  },
  {
    id: 10,
    profilePicture: "assest/persons/p6.jpg",
    username: "Jane King",
  },
  {
    id: 11,
    profilePicture: "assest/persons/p7.jpg",
    username: "Kevin Long",
  },
  {
    id: 12,
    profilePicture: "assest/persons/p8.jpg",
    username: "Laura Miller",
  },
  {
    id: 13,
    profilePicture: "assest/persons/p9.jpg",
    username: "Mike Nelson",
  },
  {
    id: 14,
    profilePicture: "assest/persons/p10.jpg",
    username: "Nora Owens",
  },

  {
    id: 15,
    profilePicture: "assest/persons/p11.jpg",
    username: "Oscar Perry",
  },
  {
    id: 16,
    profilePicture: "assest/persons/p12.jpg",
    username: "Pamela Quinn",
  },
  {
    id: 17,
    profilePicture: "assest/persons/1.jpg",
    username: "Quentin Reed",
  },
  {
    id: 18,
    profilePicture: "assest/persons/2.jpg",
    username: "Rachel Smith",
  },
  {
    id: 19,
    profilePicture: "assest/persons/3.jpg",
    username: "Steve Taylor",
  },
  {
    id: 20,
    profilePicture:"assest/persons/4.jpg",
    username: "Tina Underwood",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None. #peace #love",
    photo: "assest/posts/p1.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    desc: "Beautiful sunset at the beach today!",
    photo: "assest/posts/p2.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 15,
    comment: 2,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "assest/posts/p3.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 7,
  },
  {
    id: 4,
    desc: "My new puppy is the cutest! Meet Sparky!",
    photo: "assest/posts/p4.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 120,
    comment: 25,
  },
  {
    id: 5,
    desc: "Throwback to my trip to Paris. #tbt #travel",
    photo: "assest/posts/p5.jpg",
    date: "1 day ago",
    userId: 5,
    like: 99,
    comment: 18,
  },
  {
    id: 6,
    desc: "Coding all night. #developerlife",
    photo: "assest/posts/p6.jpg",
    date: "1 day ago",
    userId: 6,
    like: 45,
    comment: 11,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "assest/posts/p7.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    desc: "Trying out a new recipe tonight. Wish me luck!",
    photo: "assest/posts/p8.jpg",
    date: "2 days ago",
    userId: 8,
    like: 156,
    comment: 33,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo:"assest/posts/p9.jpg",
    date: "3 days ago",
    userId: 9,
    like: 88,
    comment: 10,
  },
  {
    id: 10,
    desc: "Morning hike with friends. #nature",
    photo: "assest/posts/p10.jpg",
    date: "3 days ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
  {
    id: 11,
    desc: "Just finished a great book. Highly recommend it!",
    photo: "assest/posts/p11.jpg",
    date: "4 days ago",
    userId: 11,
    like: 29,
    comment: 5,
  },
  {
    id: 12,
    desc: "Movie night! What should I watch?",
    photo: "assest/posts/p12.jpg",
    date: "5 days ago",
    userId: 12,
    like: 73,
    comment: 21,
  },
  {
    id: 13,
    desc: "The city lights are mesmerizing.",
    photo: "assest/posts/p13.jpg",
    date: "5 days ago",
    userId: 13,
    like: 91,
    comment: 14,
  },
  {
    id: 14,
    desc: "Working on a new painting. #art",
    photo: "assest/posts/p14.jpg",
    date: "6 days ago",
    userId: 14,
    like: 215,
    comment: 40,
  },
  {
    id: 15,
    desc: "Family time is the best time.",
    photo: "assest/posts/p15.jpg",
    date: "1 week ago",
    userId: 15,
    like: 130,
    comment: 22,
  },
  {
    id: 16,
    desc: "What a game! Great win by the home team.",
    photo: "assest/posts/p16.jpg",
    date: "1 week ago",
    userId: 16,
    like: 89,
    comment: 19,
  },
  {
    id: 17,
    desc: "Exploring the local market. So many treasures!",
    photo: "assest/posts/p1.jpg",
    date: "1 week ago",
    userId: 17,
    like: 67,
    comment: 6,
  },
  {
    id: 18,
    desc: "Life is what happens when you're busy making other plans.",
    photo: "assest/posts/p2.jpg",
    date: "2 weeks ago",
    userId: 18,
    like: 101,
    comment: 17,
  },
  {
    id: 19,
    desc: "Finally got my driver's license!",
    photo: "assest/posts/p3.jpg",
    date: "2 weeks ago",
    userId: 19,
    like: 150,
    comment: 30,
  },
  {
    id: 20,
    desc: "Dream big and dare to fail.",
    photo: "assest/posts/p4.jpg",
    date: "3 weeks ago",
    userId: 20,
    like: 77,
    comment: 8,
  },
];